const fs = require('fs');
const path = require('path');
const { log } = require('./logger');

const SKILLS_DIR = path.join(__dirname, '../skills');
if (!fs.existsSync(SKILLS_DIR)) fs.mkdirSync(SKILLS_DIR, { recursive: true });

// Now accepts a generic tcode variable!
function generateSkillScript(tcode, selector) {
    const scriptContent = `// AUTOGENERATED SKILL: ${tcode} Navigation
module.exports = async function navigate(page) {
    console.log("Executing learned skill: ${tcode} Navigation");
    let target = null;
    for (const frame of page.frames()) {
        const loc = frame.locator('${selector}');
        if (await loc.count() > 0) {
            target = loc.first();
            break;
        }
    }
    if (!target) throw new Error("Element ${selector} not found. UI may have changed.");
    
    await target.fill('${tcode}');
    await target.press('Enter');
};`;
    
    const skillPath = path.join(SKILLS_DIR, `skill_${tcode.toLowerCase()}.js`);
    fs.writeFileSync(skillPath, scriptContent);
    log(`Skill successfully saved to: ${skillPath}`);
}

module.exports = { generateSkillScript };