// AUTOGENERATED SKILL: ST22 Navigation
module.exports = async function navigate(page) {
    console.log("Executing learned skill: ST22 Navigation");
    let target = null;
    for (const frame of page.frames()) {
        const loc = frame.locator('id=ToolbarOkCode');
        if (await loc.count() > 0) {
            target = loc.first();
            break;
        }
    }
    if (!target) throw new Error("Element id=ToolbarOkCode not found. UI may have changed.");
    
    await target.fill('ST22');
    await target.press('Enter');
};